# Uncomment when creating a game.

# MINESWEEPER_SRC	:=	minesweeper/temp.cpp
# MINESWEEPER_OBJ	:=	$(MINESWEEPER_SRC:.cpp=.o)
# MINESWEEPER_BIN	:=	$(LIB_PATH)/arcade_minesweeper.so

# include $(BASE_DIR)/common.mk

# all:	$(MINESWEEPER_BIN)

# $(MINESWEEPER_BIN):	$(MINESWEEPER_OBJ)

all:

clean:

fclean:	clean

re:	fclean all

.PHONY:	all clean fclean re
