name: Build

on:
  push:

env:
  CORE_BINARY: arcade
  GAME_BINARIES: lib/arcade_minesweeper.so
  GRAPHICAL_BINARIES: lib/arcade_sdl2.so

jobs:
  build_core:
    name: Build Core
    if: ${{ github.repository_owner == 'hugoschool' }}
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - uses: actions/checkout@v6

      - name: Build only core
        timeout-minutes: 2
        run: make core -j`nproc`

      - name: Checking if file exist
        run: test -f ${{ env.CORE_BINARY }}

  build_games:
    name: Build Games
    if: ${{ github.repository_owner == 'hugoschool' }}
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - uses: actions/checkout@v6

      - name: Build only games
        timeout-minutes: 2
        run: make games -j`nproc`

      - name: Checking if files exist
        run: |
          for file in ${{ env.GAME_BINARIES }}; do
            test -f $file
          done

  build_graphicals:
    name: Build Graphicals
    if: ${{ github.repository_owner == 'hugoschool' }}
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - name: Install SFML v3
        run: |
          cd /tmp
          wget https://github.com/SFML/SFML/releases/download/3.0.2/SFML-3.0.2-Linux.GCC.tar.gz -O SFML.tar.gz
          mkdir SFML
          tar -xvf SFML.tar.gz -C SFML --strip-components=1
          cp -r ./SFML/lib /usr
          cp -r ./SFML/include /usr

      - uses: actions/checkout@v6

      - name: Build only graphicals
        timeout-minutes: 2
        run: make graphicals -j`nproc`

      - name: Checking if files exist
        run: |
          for file in ${{ env.GRAPHICAL_BINARIES }}; do
            test -f $file
          done
