name: cacarcade repo check

# Some of this is taken from helium repo:
# https://github.com/imputnet/helium/blob/84f7f68d2d223aa8935e242dec9ed43a7974a604/.github/actions/bump-platform/action.yml#L105

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 0/1 * * *"

  workflow_dispatch:

env:
  CHECK_REPO: freaky-family/cacarcade
  BRANCH_NAME: chore/cacarcade

jobs:
  repo_check:
    name: Check for changes
    if: ${{ github.repository_owner == 'hugoschool' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v6

      - name: Checkout repo to check
        uses: actions/checkout@v6
        with:
          repository: ${{ env.CHECK_REPO }}
          path: check-repo

      - name: Create branch and copy changes
        run: |
          git switch ${{ env.BRANCH_NAME }} || git switch -c ${{ env.BRANCH_NAME }}
          cp -r check-repo/cacarcade ./include/

      - name: Create PR if changes

        env:
          GH_TOKEN: ${{ github.token }}

        run: |
          git add include

          if ! git status | tail -1 | grep -q "nothing added to commit"; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "chore: update cacarcade"

            git push origin ${{ env.BRANCH_NAME }}
            gh pr create --title "Update cacarcade" --body ""
          else
            echo "Nothing was changed, exiting normally"
            exit 0
          fi
